name: Generate TOC

on:
  push:
    branches: [main]

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v3
        with:
          MAX_HEADER_LEVEL: 2
